#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🔧👨‍💻🔨 Styling, testing and building your project before committing 🔧👨‍💻🔨'

# Typescript
yarn style:type || (
  echo '❌🛑❌ FAILED - TYPE CHECK ❌🛑❌'
  false;
)

# Prettier
yarn style:prettier || (
  echo '❌🛑❌ FAILED - PRETTIER CHECK ❌🛑❌'
  false;
)

# ESLint
yarn style:lint || (
  echo '❌🛑❌ FAILED - ESLINT CHECK ❌🛑❌'
  false;
)

echo '🙌🛠 Trying to build now 🛠🙌'

yarn build || (
  echo '❌👷‍♂️🔨❌ FAILED - NEXT BUILD: Views the erros above to see why ❌🔨👷‍♂️❌'
  false;
)

echo '✅✨✨✅ COMMITING SUCCESS || BUILD SUCCESS ✅✨✨✅'

# git add -A . &&

yarn lint-staged
